[build]
  command = "npm run build"
  publish = "dist/hormon-calculator-frontend/browser"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
